name: winter_framework
description: A rest framework for create lightweight services
version: 0.0.0
repository: https://github.com/JesusHdez960717/winter_framework.git

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_multipart: ^2.0.0

  #para el parseo a snack case
  change_case: ^2.1.0

  #para el parsea del media type
  string_scanner: ^1.3.0
  http_parser: ^4.1.0

  mongo_dart: ^0.10.3

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
