name: winter
description: This project is designed to create server side apps the simplest way possible, and reduce the learning curve in backend development.
version: 0.0.3
repository: https://github.com/Root-101/winter

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_multipart: ^2.0.0

  #Utils
  collection: ^1.19.1

  #For naming strategy
  change_case: ^2.1.0

  #For media type parsing
  string_scanner: ^1.3.0
  http_parser: ^4.1.0

  mongo_dart: ^0.10.3

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
